version: '3'

services:
  web:
    image: stackdemo:v1
    build: 
      context: ./
      dockerfile: Dockerfile-web
    deploy:
      replicas: 3
    ports:
      - "8000"
  redis:
    image: redis:alpine
  nginx:
    image: nginx:alpine
    ports:
      - "9100:80"  # Expose Nginx on port 9000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Load custom Nginx configuration file
    depends_on:
      - web